admin_systeminfo:
    path: /sysinfo
    defaults:
        _controller: ezsystems.ezsupporttools.controller.systeminfo:infoAction
    methods: [GET]

admin_phpinfo:
    path: /sysinfo/phpinfo
    defaults:
        _controller: ezsystems.ezsupporttools.controller.systeminfo:phpinfoAction
    methods: [GET]
