parameters:
    ezsystems.ezsupporttools.controller.systeminfo.class: EzSystems\EzSupportToolsBundle\Controller\SystemInfoController
    ezsystems.ezsupporttools.infoprovider.composer_infoprovider.class: EzSystems\EzSupportToolsBundle\InfoProvider\ComposerInfoProvider
    ezsystems.ezsupporttools.infoprovider.ezplatform_infoprovider.class: EzSystems\EzSupportToolsBundle\InfoProvider\EzPlatformInfoProvider
    ezsystems.ezsupporttools.infoprovider.system_infoprovider.class: EzSystems\EzSupportToolsBundle\InfoProvider\SystemInfoProvider

services:
    ezsystems.ezsupporttools.infoprovider.composer_infoprovider:
        class: %ezsystems.ezsupporttools.infoprovider.composer_infoprovider.class%
        arguments:
            - 'eZSupportTools:InfoProvider:composer.html.twig'
            - "%kernel.root_dir%/../"

    ezsystems.ezsupporttools.infoprovider.ezplatform_infoprovider:
        class: %ezsystems.ezsupporttools.infoprovider.ezplatform_infoprovider.class%
        arguments:
            - 'eZSupportTools:InfoProvider:ezplatform.html.twig'
            - %kernel.bundles%

    ezsystems.ezsupporttools.infoprovider.system_infoprovider:
        class: %ezsystems.ezsupporttools.infoprovider.system_infoprovider.class%
        arguments:
            - 'eZSupportTools:InfoProvider:system.html.twig'
            - @database_connection

    ezsystems.ezsupporttools.controller.systeminfo:
        class: %ezsystems.ezsupporttools.controller.systeminfo.class%
        arguments:
            - @ezsystems.ezsupporttools.infoprovider.ezplatform_infoprovider
            - @ezsystems.ezsupporttools.infoprovider.system_infoprovider
            - @ezsystems.ezsupporttools.infoprovider.composer_infoprovider
        parent: ezsystems.platformui.controller.base
